
-- Insertar los datos
INSERT INTO column_type (id,name, aliases, description)
VALUES
    (1, 'integer', 'bigint', 'Integers represent whole numbers, e.g., 1, 2, -3.'),
    (2, 'bigserial', 'bigserial', 'BIGSERIAL is an auto-incrementing integer type.'),
    (3, 'bit', 'bit', 'BIT is used to store bit strings.'),
    (4, 'box', 'box', 'BOX represents a rectangular box in a plane.'),
    (5, 'bytea', 'bytea', 'BYTEA is used to store binary data.'),
    (6, 'cidr', 'cidr', 'CIDR represents an IPv4 or IPv6 network address.'),
    (7, 'circle', 'circle', 'CIRCLE represents a circle in a plane.'),
    (8, 'double', 'double', 'DOUBLE is used to store double-precision floating-point numbers.'),
    (9, 'inet', 'inet', 'INET represents an IPv4 or IPv6 host address.'),
    (10, 'interval', 'interval', 'INTERVAL represents a time duration.'),
    (11, 'json', 'json', 'JSON stores JSON-formatted data.'),
    (12, 'jsonb', 'jsonb', 'JSONB stores JSON data in a binary format.'),
    (13, 'line', 'line', 'LINE represents an infinite straight line in a plane.'),
    (14, 'lseg', 'lseg', 'LSEG represents a line segment in a plane.'),
    (15, 'macaddr', 'macaddr', 'MACADDR represents a MAC address.'),
    (16, 'macaddr8', 'macaddr8', 'MACADDR8 represents an 8-byte MAC address.'),
    (17, 'money', 'money', 'MONEY stores currency amounts.'),
    (18, 'numeric', 'numeric', 'NUMERIC stores arbitrary precision numbers.'),
    (19, 'path', 'path', 'PATH represents a closed geometric path in a plane.'),
    (20, 'point', 'point', 'POINT represents a point in a plane.'),
    (21, 'polygon', 'polygon', 'POLYGON represents a closed geometric polygon in a plane.'),
    (22, 'real', 'real', 'REAL is used to store single-precision floating-point numbers.'),
    (23, 'smallint', 'smallint', 'SMALLINT represents small integers.'),
    (24, 'smallserial', 'smallserial', 'SMALLSERIAL is an auto-incrementing small integer type.'),
    (25, 'serial', 'serial', 'SERIAL is an auto-incrementing integer type.'),
    (26, 'text', 'text', 'TEXT is used to store variable-length character strings.'),
    (27, 'time', 'time', 'TIME represents a time of day without a date.'),
    (28, 'timestamp', 'timestamp', 'TIMESTAMP represents a date and time.'),
    (29, 'tsquery', 'tsquery', 'TSQUERY represents a text search query.'),
    (30, 'tsvector', 'tsvector', 'TSVECTOR represents a text search document.'),
    (31, 'uuid', 'uuid', 'UUID stores Universally Unique Identifiers.'),
    (32, 'xml', 'xml', 'XML stores XML data.');
